// src/lib/components/LastFmForm.svelte
<script lang="ts">	import { goto } from '$app/navigation';
	import { lastFmFormSchema, type LastFmFormValues } from '$lib/schemas.js';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Switch } from '$lib/components/ui/switch';

	let formData: LastFmFormValues = {
		apiKey: '',
		username: '',
		useOptimized: false
	};

	let errors: Partial<Record<keyof LastFmFormValues, string>> = {};

	function validateForm(): boolean {
		try {
			lastFmFormSchema.parse(formData);
			errors = {};
			return true;
		} catch (error: any) {
			errors = {};
			if (error.errors) {
				error.errors.forEach((err: any) => {
					errors[err.path[0] as keyof LastFmFormValues] = err.message;
				});
			}
			return false;
		}
	}

	function onSubmit() {
		if (!validateForm()) return;

		const baseUrl = formData.useOptimized ? "/optimized-waves" : "/waves";
		const url = new URL(baseUrl, window.location.origin);
		url.searchParams.set("apiKey", formData.apiKey);
		url.searchParams.set("username", formData.username);
		goto(url.toString());
	}
</script>

<form on:submit|preventDefault={onSubmit} class="space-y-8">
	<div class="space-y-2">
		<Label for="apiKey">LastFM API Key</Label>
		<Input
			id="apiKey"
			placeholder="Enter your LastFM API key"
			bind:value={formData.apiKey}
		/>
		<p class="text-[0.8rem] text-muted-foreground">
			Your LastFM API key from last.fm/api
		</p>
		{#if errors.apiKey}
			<p class="text-[0.8rem] font-medium text-destructive">{errors.apiKey}</p>
		{/if}
	</div>

	<div class="space-y-2">
		<Label for="username">LastFM Username</Label>
		<Input
			id="username"
			placeholder="Your LastFM username"
			bind:value={formData.username}
		/>
		{#if errors.username}
			<p class="text-[0.8rem] font-medium text-destructive">{errors.username}</p>
		{/if}
	</div>

	<div class="flex flex-row items-center justify-between rounded-lg border p-4">
		<div class="space-y-0.5">
			<Label class="text-base">Use Optimized Version</Label>
			<p class="text-[0.8rem] text-muted-foreground">
				Enable for enhanced performance visualization
			</p>
		</div>
		<Switch bind:checked={formData.useOptimized} />
	</div>

	<Button type="submit">View Visualizer</Button>
</form>

// src/components/LastFmForm.tsx
"use client"

import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { useRouter } from "next/navigation"
import { LastFmFormValues, lastFmFormSchema } from "@/lib/schemas"
import { Button } from "@/components/ui/button"
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { Switch } from "@/components/ui/switch"

export function LastFmForm() {
  const router = useRouter()
  const form = useForm<LastFmFormValues>({
    resolver: zodResolver(lastFmFormSchema),
    defaultValues: {
      apiKey: "",
      username: "",
      useOptimized: false,
    },
  })

  function onSubmit(data: LastFmFormValues) {
    const baseUrl = data.useOptimized ? "/optimized-waves" : "/waves"
    const url = new URL(baseUrl, window.location.origin)
    url.searchParams.set("apiKey", data.apiKey)
    url.searchParams.set("username", data.username)
    router.push(url.toString())
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
        <FormField
          control={form.control}
          name="apiKey"
          render={({ field }) => (
            <FormItem>
              <FormLabel>LastFM API Key</FormLabel>
              <FormControl>
                <Input placeholder="Enter your LastFM API key" {...field} />
              </FormControl>
              <FormDescription>
                Your LastFM API key from last.fm/api
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="username"
          render={({ field }) => (
            <FormItem>
              <FormLabel>LastFM Username</FormLabel>
              <FormControl>
                <Input placeholder="Your LastFM username" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="useOptimized"
          render={({ field }) => (
            <FormItem className="flex flex-row items-center justify-between rounded-lg border p-4">
              <div className="space-y-0.5">
                <FormLabel className="text-base">Use Optimized Version</FormLabel>
                <FormDescription>
                  Enable for enhanced performance visualization
                </FormDescription>
              </div>
              <FormControl>
                <Switch
                  checked={field.value}
                  onCheckedChange={field.onChange}
                />
              </FormControl>
            </FormItem>
          )}
        />
        <Button type="submit">View Visualizer</Button>
      </form>
    </Form>
  )
}
